chore: migrate from k8s.gcr.io to registry.k8s.io
cdk8s-team/cdk8s-core pull request #1172
Opened 2023-04-12 12:35 UTC by ahmedwaleedmalik

Kubernetes is migrating its image registry from [k8s.gcr.io](http://k8s.gcr.io/) to [registry.k8s.io](http://registry.k8s.io/).

Part of kubernetes/k8s.io#4780.

2023-04-13 08:08 UTC, ahmedwaleedmalik commented
@mrgrain can you PTAL?

2023-04-13 16:40 UTC, vinayak-kukreja requested changes
Hey, thank you for your contribution. Just a minor comment.

2023-04-13 16:40 UTC, vinayak-kukreja commented on test/fixtures/guestbook-all-in-one.yaml
> +    - port: 6379
Hey, please remove these additional spaces.

2023-04-13 18:16 UTC, vinayak-kukreja commented
Looks like build is failing for mutation since this was originated from a fork. Could you update your branch?

```
Run echo "::error::Files were changed during build (see build log). If this was triggered from a fork, you will need to update your branch."
  echo "::error::Files were changed during build (see build log). If this was triggered from a fork, you will need to update your branch."
  cat .repo.patch
  exit 1
  shell: /usr/bin/bash -e {0}
  env:
    CI: true
Error: Files were changed during build (see build log). If this was triggered from a fork, you will need to update your branch.
diff --git a/test/__snapshots__/yaml.test.ts.snap b/test/__snapshots__/yaml.test.ts.snap
index dd2e186..f6c89c0 100644
--- a/test/__snapshots__/yaml.test.ts.snap
+++ b/test/__snapshots__/yaml.test.ts.snap
@@ -87,7 +87,7 @@ Array [
         "spec": Object {
           "containers": Array [
             Object {
-              "image": "registry.k8s.io/redis:e2e",
+              "image": "k8s.gcr.io/redis:e2e",
               "name": "master",
               "ports": Array [
                 Object {
Error: Process completed with exit code 1.

2023-04-17 06:48 UTC, ahmedwaleedmalik commented on test/fixtures/guestbook-all-in-one.yaml
> +    - port: 6379
Updated, PTAL.

2023-04-17 19:12 UTC, vinayak-kukreja approved these changes

2023-04-17 19:36 UTC, vinayak-kukreja commented
Hey, @ahmedwaleedmalik, our build step cannot run on a fork. Could you run `yarn build` on your fork and update here.

2023-04-19 09:15 UTC, ahmedwaleedmalik commented
> Hey, @ahmedwaleedmalik, our build step cannot run on a fork. Could you run `yarn build` on your fork and update here.

Not sure what you want from me here? Do you want me to build it and check if it's working? Then yes, i was able to build it.

2023-05-16 19:16 UTC, vinayak-kukreja commented
Hey @ahmedwaleedmalik, we have taken care of this issue and would be closing this PR now. 

We thank you for your contribution and bringing visibility into this. Really appreciate it. :)

2023-05-16 19:16 UTC, closed without merging

2023-05-16 19:18 UTC, ahmedwaleedmalik commented
> Hey @ahmedwaleedmalik, we have taken care of this issue and would be closing this PR now.
> 
> We thank you for your contribution and bringing visibility into this. Really appreciate it. :)

So the maintainers didn't bother to reply for a month and then just closed the PR. Seems like you folks are very "open source" friendly.